name: Master branch CI

on:
  push:
    branches:
      - 'master'

jobs:
  test:
    name: JUnit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: ./gradlew testDebug
        env:
          tmdb_api_key: '"TMDB_API_KEY"'
